// <auto-generated />
using EnterpriseSchema.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseSchema.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EnterpriseSchema.Models.Access", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConfigContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EnterpriseId")
                        .HasColumnType("int");

                    b.Property<int?>("HostId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("HostId");

                    b.ToTable("Accesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "vpn.stacklabs.ru",
                            ConfigContent = "Пути к развернутым службам",
                            EnterpriseId = 1,
                            Login = "login",
                            Note = "Заметка1",
                            Pass = "pass",
                            Port = 1111,
                            Type = "VPN"
                        },
                        new
                        {
                            Id = 2,
                            Address = "192.168.0.10",
                            ConfigContent = "Пути к развернутым службам",
                            HostId = 1,
                            Login = "root",
                            Note = "Заметка2",
                            Pass = "pass",
                            Port = 22,
                            Type = "SSH"
                        },
                        new
                        {
                            Id = 3,
                            Address = "192.168.0.20",
                            ConfigContent = "Пути к развернутым службам",
                            HostId = 1,
                            Login = "root",
                            Note = "Заметка3",
                            Pass = "pass",
                            Port = 3306,
                            Type = "DB"
                        });
                });

            modelBuilder.Entity("EnterpriseSchema.Models.Enterprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Enterprises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Курган",
                            Contact = "Иванов Иван Иванович",
                            Name = "Завод1",
                            Note = "Заметка1"
                        },
                        new
                        {
                            Id = 2,
                            City = "Челябинск",
                            Contact = "Петров Петр Петрович",
                            Name = "Завод2",
                            Note = "Заметка2"
                        });
                });

            modelBuilder.Entity("EnterpriseSchema.Models.Host", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NetworkInterfaces")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServicesInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("Hosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnterpriseId = 1,
                            Ip = "192.168.0.1",
                            Name = "Сервер1",
                            NetworkInterfaces = "IfConfig output",
                            Notes = "Свободное поле",
                            Os = "Ubuntu 22 LTS",
                            ServicesInfo = "Службы",
                            Target = "СЦ (BluePyramid)"
                        },
                        new
                        {
                            Id = 2,
                            EnterpriseId = 1,
                            Ip = "192.168.0.2",
                            Name = "Сервер2",
                            NetworkInterfaces = "IfConfig output",
                            Notes = "Свободное поле",
                            Os = "Debian 12",
                            ServicesInfo = "Службы",
                            Target = "СВ (Веб интерфейс)"
                        });
                });

            modelBuilder.Entity("EnterpriseSchema.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "login",
                            Name = "Владимир Дмитриевич",
                            Pass = "pass"
                        });
                });

            modelBuilder.Entity("EnterpriseSchema.Models.Access", b =>
                {
                    b.HasOne("EnterpriseSchema.Models.Enterprise", "Enterprise")
                        .WithMany("Accesses")
                        .HasForeignKey("EnterpriseId");

                    b.HasOne("EnterpriseSchema.Models.Host", "Hosts")
                        .WithMany("Accesses")
                        .HasForeignKey("HostId");

                    b.Navigation("Enterprise");

                    b.Navigation("Hosts");
                });

            modelBuilder.Entity("EnterpriseSchema.Models.Host", b =>
                {
                    b.HasOne("EnterpriseSchema.Models.Enterprise", "Enterprise")
                        .WithMany("Hosts")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("EnterpriseSchema.Models.Enterprise", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("Hosts");
                });

            modelBuilder.Entity("EnterpriseSchema.Models.Host", b =>
                {
                    b.Navigation("Accesses");
                });
#pragma warning restore 612, 618
        }
    }
}
